#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long S_l, long long T_l, long long X_l){
    int S = S_l;
    int T = T_l;
    int X = X_l;
    if ( S > T) {
        S = S;
        if (X < T) {
            X = 24 + X;
        }
        T = 24 + T;
    }


    if ( S <= X && T > X) {
        cout << "Yes" << endl;
    } else {
        cout << "No" << endl;
    }
}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long S;
    std::scanf("%lld", &S);
    long long T;
    std::scanf("%lld", &T);
    long long X;
    std::scanf("%lld", &X);
    solve(S, T, X);
    return 0;
}
