#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, std::vector<long long> L){
    std::sort(L.begin(),L.end());
    int sum = 0;
    for (int i=0; i<=L.size();i+=2) {
        if (i+1<=L.size()) {
            sum += L.at(i);
        }
    }
    cout << sum << endl;
}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> L(2*N);
    for(int i = 0 ; i < 2*N ; i++){
        std::scanf("%lld", &L[i]);
    }
    solve(N, std::move(L));
    return 0;
}
