#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long N, std::vector<std::vector<long long> > D){
    int i = 0;
    for (vector<long long> vec : D) {
        long d1 = vec.at(0);
        long d2 = vec.at(1);
        if (d1==d2) {
            i += 1;
            if (i >= 3) {
                cout << "Yes" << endl;
                return;
            }
        } else {
            i = 0;
        }
    }
    cout << "No" << endl;
}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    std::vector<std::vector<long long> > D(N, std::vector<long long>(2));
    for(int i = 0 ; i < N ; i++){
        for(int j = 0 ; j < 2 ; j++){
            std::scanf("%lld", &D[i][j]);
        }
    }
    solve(N, std::move(D));
    return 0;
}
