#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
#define rep(i, n) for (int i = 0; i < (int)(n); i++)
#define all(x) (x).begin(),(x).end()
using ll = long long;
using vl = vector<long long>;
#ifdef _DEBUG
#define debug(x) cerr << "[DEBUG] " << __LINE__ << ": " << #x << " = " << x << endl
#else
#define debug(x)
#endif

void solve(long long N, std::vector<std::string> S, std::vector<long long> T){
    map<string, ll> originals;
    rep(i, N) {
        ll val = N-i-1;
        string poem = S.at(val);
        originals[poem]=val;
    }

    map<ll, ll> map; // id : points

    for (pair<string, ll> pr : originals) {
        map[pr.second] = T.at(pr.second);
    }

    auto pr = std::max_element
            (
                    all(map),
                    [] (const decltype(map)::value_type & p1, const decltype(map)::value_type & p2) {
                        return p1.second < p2.second;
                    }
            );

    cout << pr->first+1 << endl;


}

// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    std::vector<std::string> S(N);
    std::vector<long long> T(N);
    for(int i = 0 ; i < N ; i++){
        std::cin >> S[i];
        std::scanf("%lld", &T[i]);
    }
    solve(N, std::move(S), std::move(T));
    return 0;
}
